REGISTRY?=icr.io/ai-services-private
IMAGE=minio
MINIO_RELEASE=RELEASE.2025-10-15T17-29-55Z
TAG?=${MINIO_RELEASE}

CONTAINER_BUILDER?=podman
build:
	$(CONTAINER_BUILDER) build --pull=always --build-arg MINIO_RELEASE=${MINIO_RELEASE} -t $(REGISTRY)/$(IMAGE):$(TAG) .
.PHONY: build

push:
	$(CONTAINER_BUILDER) push $(REGISTRY)/$(IMAGE):$(TAG)
.PHONY: push
