ui:
  port: ""
  image: icr.io/ai-services-cicd/catalog-ui:v0.0.3

backend:
  port: ""
  image: icr.io/ai-services-cicd/ai-services:0.0.4
  runtime: ""
  adminPasswordHash: ""
  podman:
    uri: "/run/podman/podman.sock"

db:
  port: ""
  image: icr.io/ai-services-private/postgres:18
  user: "admin"
  database: "ai_services"
  password: ""
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"

caddy:
  image: "docker.io/library/caddy:2.8-alpine"
  # @description https port for caddy. If unspecified, a random available port is assigned. Specify a port number to use a custom value.
  httpsPort: ""
  # @description admin port for caddy. If unspecified, a random available port is assigned. Specify a port number to use a custom value.
  adminPort: ""
