FROM registry.access.redhat.com/ubi9/nodejs-22:9.6 AS builder

# Set the working directory.
WORKDIR /app

# Switch to root to install global tools
USER 0
RUN npm install -g yarn

# Change its ownership to the non-root user.
RUN mkdir -p /app && chown -R 1001:0 /app

# Switch to the non-root user
USER 1001

# Copy package files first to leverage build cache
COPY package.json yarn.lock ./

# Install dependencies and build
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# Stage 2: Production image with NGINX on UBI
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6

RUN microdnf install -y nginx gettext && \
    microdnf clean all && \
    rm -rf /var/cache/dnf && \
    mkdir -p /var/log/nginx && \
    chown -R nginx:root /var/log/nginx

# Nginx config
RUN rm -rf /etc/nginx/conf.d
COPY --chown=nginx:root conf /etc/nginx
COPY --chown=nginx:root nginx.conf /etc/nginx

# Copy dist build
COPY --from=builder /app/dist /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html
COPY ./entrypoint.sh .

# Set correct permissions for nginx to serve content
RUN chown -R nginx:root /usr/share/nginx/html

EXPOSE 8080
CMD ["/bin/bash", "/usr/share/nginx/html/entrypoint.sh"]
